language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

addons:
  apt:
    packages: gfortran

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then
    brew update > /dev/null;
    brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
  fi

install:
- pip install -e .[tests]

- cd bin
- cmake ..
- cmake --build .

script:
- ctest -R basic -V
- cd ..

- pytest -xrsv
- flake8
- mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi
